### PR TITLE
Read cache speedup

### PR DESCRIPTION
**Pull request by gyurco**
0 delay reads for up to 64 bits from the last used cacheline.

Sysinfo speed increase is enormous.
Doom is much better.
Syndicate in Shapehifter is slightly better, I think the problem is the write speed to the video ram. Would be good to have a 0 delay writebuffer.

### CODE REVIEW

**Comment by gyurco** [comment]
- Added the video clock switching (28/114 MHz) to chipset/RTG video.
- Reconfigurable PLL: I don't know how portable the PLL reconfig megafunctions between devices. Maybe only the MIFs should be different. If even the glue logic is not usable, then the MINIMIG_ALTERA_PLL_RECONFIG should be renamed to MINIMIG_ALTERA_CYCLONEIII_PLL_RECONFIG or similar. The override from mist.ini is not added yet, that needs a little firmware and user_io change.

**Comment by robinsonb5** [comment]
Annoyingly github didn't bother to notify me of this pull request so I didn't know it was here until you mentioned it in Julitium's bug - but wow!  Awesome!  Thanks for that.

I've also been hacking on this, from a different angle - if you look at my "glue2" branch I have a version that doesn't attempt to improve reads, but does decouple the fast RAM mechanism from the 28MHz clkena, and does mean that the two clkena's of 32-bit writes are only four cycles apart.  Hopefully merging these two approaches won't be too painful!

**Comment by robinsonb5** [comment]
As for the reconfigurable PLL - if they're anything like the regular PLLs then for ChameleonV2 and DE10 lite they'll be basically the same except the target device fields will need to be changed to "Cyclone10LP" or "MAX10".  The .mifs will be unique to the target platforms of course, mostly because their incoming master clocks vary.

**Comment by gyurco** [comment]
> Annoyingly github didn't bother to notify me of this pull request so I didn't know it was here until you mentioned it in Julitium's bug - but wow! Awesome! Thanks for that.
> 
> I've also been hacking on this, from a different angle - if you look at my "glue2" branch I have a version that doesn't attempt to improve reads, but does decouple the fast RAM mechanism from the 28MHz clkena, and does mean that the two clkena's of 32-bit writes are only four cycles apart. Hopefully merging these two approaches won't be too painful!

Oh, that would be good. I just started to think about to ack the first word of the 32 bit write immediately (even don't wait for the cache), but I'll wait until your approach is in place. The zero-delay reads boosted sysinfo score by almost 50% (which seems unbelievable, however it's very noticeable in real-world games), faster longword writes should make the core blazing fast.

>
>As for the reconfigurable PLL - if they're anything like the regular PLLs then for ChameleonV2 and DE10 lite they'll be basically the same except the target device fields will need to be changed to "Cyclone10LP" or "MAX10". The .mifs will be unique to the target platforms of course, mostly because their incoming master clocks vary.

That would be really good, if only the megafunctions with changed parameters and the MIFs have be put in the target dir. The PLL itself is the standard one, just some more in-out signals are enabled. There's a helper megafunction, called ALTPLL_RECONFIG which adjust the base PLL via those extra signals with the data read from the ROMs. Just I'm not sure if these are pin-compatible between Quartus/device versions.

**Comment by gyurco** [comment]
As I've checked your glue2 branch, I don't see much conflicts with my changes, mine is mostly about the read cache, yours mostly about the writebuffer, so fingers crossed.

**Pull request merged**
